# -*- coding: utf-8 -*-


__all__ = ["DEFAULT_WORKFLOWY_URL", "DEFAULT_ROOT_NODE_ID",
           "DEFAULT_WORKFLOWY_CLIENT_VERSION", "DEFAULT_WORKFLOWY_MONTH_QUOTA"]

DEFAULT_WORKFLOWY_URL = "https://workflowy.com/"
DEFAULT_ROOT_NODE_ID = "None"

DEFAULT_WORKFLOWY_CLIENT_VERSION = 18  # @ 2017-10-04
DEFAULT_WORKFLOWY_MONTH_QUOTA = 250
